### ISSUE TITLE
Protection from Fire and Ice buff Icon

### ISSUE THREAD

**Issue by SlysterLOK** [jkachhad/Stormhalter#10]
The Buff Icon ( what shows up on players buff bar ) should be the same as the Spell Icon.

**Comment by jkachhad** [comment]
Unfortunately, I don't think I will be able to support "combined" protections when single protections exist. On Lands of Kes, when you gain a buff through a spell, and equip an item that provides a similar buff, the spell component is overwritten. I had initially implemented it that way.

In the current implementation, when being provided a buff with a spell, or item, the components can exist independent of each other. Such that, when the item is removed, the spell will still be considered active and provide protection.

Protection from Fire/Ice provides both protections, visible as each individual icon. The reason that Stun/Death combination is supported is because it's a protection vs Resist from Stun or Death.

I'll see if in the future we can support the correct icon. For now it'll be low priority as the mechanic itself works correctly, just displayed incorrectly.

**Comment by SlysterLOK** [comment]
Sounds good. I just didn't know if it was just a graphical change.
