### ISSUE TITLE
broken stamina regen speedleveling

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1092]
This might be related to the bug that Mose put in.  When speed leveling a new character, Stamina regeneration can break entirely when the game sort of thinks you're supposed to be at a different level than your current. [Reported by Vernak]

**Comment by Chilly021** [comment]
Does this still occur? @Tawnos-LOK

**Comment by jkachhad** [comment]
In this image, I used to peek to check his vision. he could not see me 2 hexes away.
![image](https://user-images.githubusercontent.com/1934897/155899357-d6719b87-da7f-4ca5-ae73-1ef0cfc07839.png)

In this image, I did similar, but he could see me 1 hex away since he has night vision.
![image](https://user-images.githubusercontent.com/1934897/155899455-5e7a5102-5c28-4e39-8359-be3377dabeee.png)

Doesn't appear this is an issue anymore.
