### ISSUE TITLE
Lightning Storm & LOS

### ISSUE THREAD

**Issue by jkachhad** [jkachhad/Stormhalter#116]
Currently, all spells are implemented based off their description in the LOK help file. A few players have mentioned that they should not be hit by certain spells when casting, specifically if out of LOS.

I never had an opportunity to see Lightning Storm on GS, and can't recall anything specific from Lands of Kes, does it obey LOS from the locus?

**Comment by SlysterLOK** [comment]
I dont remember. I know firestorm grew around corners and such but LS I dont know if it went around or over walls and such

**Comment by dedmist** [comment]
I have a lor of thaumahawk casting LS, it doesn't show a whole lot because she casts off screen.  It's supposed to be a 7x7 hub and spoke.  So it's LOS from the epicenter.  FS is the same spell, only casting a random 1x1 or 3x3 fireball on each hex radiating out from the center.  In the Olorin replay I have, I see it going around corners only as far as 1 tile further than LOS (the last LOS tile is hit by a 3x3)

**Comment by RPSwick** [comment]
My LoK wizard has firestorm.  It does the 7x7 area with fire but only LoS from the starting point.  U could cast it around corners and then not be hit by it.  Same with LS I believe but my Thaum needs 50% more in current skill to verify.

**Comment by jkachhad** [comment]
I current have this spreadsheet, the person helping me collect data may be a bit busy at the moment. If anyone would like to go through it and let me know the LOS rules, I can implement them similarly. Feel free to add spells or adjust columns for more information.

https://docs.google.com/spreadsheets/d/1dQXtuloDT6UwoXnNyKzlMFIRij-h7cqf9cwBm_qdLQY/edit?usp=sharing
