### ISSUE TITLE
Make caster buffs persistent Auras

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1351]
To combat short duration buff issues with casters, make the buffs infinite duration but have them “reserve” their mana cost as an aura that can be removed when desired. With the bigger spells like stun/death protection it’d still drive you to collect the items since casting it on 2-3 people would use most your mana. [Suggested by Wirednuke]

**Comment by dedmist** [comment]
Since buffs are mana positive at the end of their duration, I think this would have negative impact on the hunting buffs and only situational impact on buffs that could be done with an item.
Like shield or strength would be a way to free up an item slot for very little mana, but f/i, s/d, pp, perception would be burdensome to upkeep and very situational.
I think we'd be better off with a more favorable progression of buff timer.
Honestly, for the buffs that you can get from items, these don't really serve as much purpose in the game anymore, it'd be good to either make them more useful in hunting or replace them with something better.  For general hunting, they just don't last long enough.  There's a usecase for pp at thisson while wearing S/D or the occasional FF when someone forgets theirs.

I guess I'm proposing a usecase, like a hunting area with pretty bad poison + s/d, or needs 4 shielders and 4 str plus f/b and power bracer etc and durations that scale to 30 minutes.

**Comment by Tenscore** [comment]
i oppose removing them for the simple fact that they can be useful until the items are acquired in the low level game.
but the short duration absolutely destroys their functionality.

i also feel like the buffs should be slightly better than their jewelry counterparts in the higher level game.
Situational, yes - maybe.  Useless, no.
just my 2c.

**Comment by dedmist** [comment]
in OG AG the buffs were pretty useful because of the rarity and level of the items that would replace them.  F/B and D/S should probably go closer to 14 instead of 17 and 19 respectively.  There isn't much of a need for tradeoffs with the way OG BG is structured.

**Comment by jkachhad** [comment]
```
Duration of all Resistance and Protection spells have been doubled.
```

Not sure if this an issue anymore. Closing. Can create new issue if still not properly tuned.
