### ISSUE TITLE
mobs don't move out of aoe

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1374]
On a wizard, mobs make no effort to step out of an aoe. I can cast my level 2 spell bonfire on any ranged mob and have a guarenteed kill for 3 mana. They'll just stand in it and roast, there's almost no reason to use any other spell. [Reported by Wirednuke]

**Comment by bsmittyau7** [comment]
This isn’t the case in my experience. Any mobs who normally flee when near death will flee from bonfire. Orcs and trolls in particular. Goblins will sit and roast.

**Comment by Tenscore** [comment]
This issue is similar to #1375, and should probably be closed.
AOE's, rightfully, should issue a chance of - "Confused by fire", "Slipped on ice", and whatever message Whirlwind used.
Especially if the mobs are going to actively try and avoid/jump out of them.
For wizzies, in particular, things are pretty tough all around.

**Comment by Chilly021** [comment]
A little ambiguity here. I think this is the same issue as Tenser mentioned.
