### ISSUE TITLE
nerf enchant weapon

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1427]
the amount of benefit enchant weapon provides is insanely good. I have a 17/14 wizard with raxe in axe undead level where mobs gives 30k exp each… with no enchant, I miss frequently, am blocked by armor frequently, and land shots maybe 10% of the time. With weapon enchant, I never miss and am rarely blocked, and slice through the mobs in 4-5 throws. It should provide some benefit for using, but it shouldn’t be a god mode spell that people refuse to hunt without. [Suggested by Smitty]

**Comment by dedmist** [comment]
It seems like it would be more balanced to have to be level X to even add +1 to a +4 weapon.  And should probably only be good for so long.

**Comment by dedmist** [comment]
Second thought: maybe we could change this to an aura that helps hitting a certain boss that can be cast on any char.  Make it more situational, but still useful.
If it's fixing the gap between Knight and MA, this would 1: mean that wiz/thief would be generally further behind; 2: be another barrier to MA skill on nonMAs; 3: will make balancing much more difficult due to inconsistencies in expected equipment

**Comment by Chilly021** [comment]
I think with fumble this might do the job for now. Let's re-evaluate later.
