### ISSUE TITLE
can anti scripting changes not interfere with strategic gameplay please?

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1506]
I’m all for no scripting, but some of these changes lately are going pretty crazy. Gargoyles were added in -300 and then removed in exchange for a lurker, which is far more reasonable.  Even with the lurker, the additional pillar remains in the water?  Who is approving all these willy nilly changes but won’t approve Brick’s thief trainer in lockpick town?  Anti scripting changes are great, but hunting from -300 water is a legitimate tactic that should be available to people. If you can’t curb scripters without effecting regular players, it’s a bad change. Just ban the damn scripters and leave the rest of us alone please. [Reported by Smitty]

**Comment by dedmist** [comment]
The thief trainer became redundant with a new way of carrying unlimited gold.

The changes are to disincentivize not playing the game.  There are also a number of rewards for actually hunting.  If sitting in water throwing WW/rweap is the most effective way to play the game then there's something wrong and we need to change it.  So, if we consider that the reason to sit in the water with less risk is to eventually hunt in areas with more risk then we are changing the risk/reward process to facilitate this.  Really, -300 is a badly designed area, the water should have indestructible walls around it and a short maze around the entrance to the level.  We don't change this because it was original to the game but you can see that it encourages a "strategy" that we're trying to make less rewarding.  Plinking and blind casting should be less lucrative.

Now I guess you're asking why this matters?  Why should we care if people want to play in a boring way?  The same reason that the game needs to be difficult without being punishing, we want the game to be more engaging.  Boredom sets in with the puddle hunting methods and with content that's too easy.  Engaging content is what people come back for, but it's easy to get stuck in the rut of boredom grinding then leave for extended periods of time.

We're not going to really prevent this behavior, but we are going to make you have to deal with a lurker from time to time.

I think we're not prepared to kick out members of the community even for scripting, it's more about community than the game even.

**Comment by bsmittyau7** [comment]
There are times when full attention is not available, but casting down a mana bar every few minutes is possible. It’s nice to have options to be able to play in that situation rather than just towncast, even if the gains are terrible. The only thing you’re really encouraging or discouraging by making the puddle so miserable is that I may decide to logout when I would’ve otherwise stayed logged in to burn mana, if I’m being honest.  If the only option for “distracted” gameplay is being in town, you’re losing some people.

**Comment by dedmist** [comment]
That's understandable, but I think there needs to be a more appropriate place to do this.  -300 has very high XP and loot values (on par with speedy) but the proposal is to be able to cast there with little to no risk.  It's easy enough to take advantage of the game mechanics already and cast with lowered attention in a lot of places.

I'm up for options, how do we balance out the risk vs reward of the 100% casual gameplay area?  

I don't see a problem with making a casting area for casual styles, maybe people could tell me where they want it and what it should look like and how much XP/gold gain they should expect for burning mana.  Maybe an open water area in the leng pit surrounded by some lower level mobs with appropriate gold and xp?  Can even put the stairs right in the middle of the water for convenience.

Is the puddle actually miserable to play in?  Or you mean that it's inconvenient and distracted play can lead to dying?  We should probably remove the IS immunity, not sure why that's in, but otherwise I don't expect it to be much of a hardship.  The thought on switching to lurkers is that you wouldn't end up pinata-ed all over -300 from the gargs.

**Comment by bsmittyau7** [comment]
The only problems I have currently with the setup in -300 is the pillar being unnecessary and the lurker being IS immune.  The lurker is the guarantee that nobody will script there.  I can already WW hunt more effectively in -50 and -100 when the game has my full attention with a chance at getting a high value bar.  If everything in -300 was worth half what it is now I’d still try to hunt it the same way… it’s less about what’s currently in the area and more about wanting to be able to get SOME value from playing without just towncasting somewhere.  It’s also wide open with no walls so the mobs just jump out of the WWs for the most part. But I’d rather see if I can WW some area half paying attention for an hour and then try to scoop the loot and leave.  The suggestion for other areas to serve this purpose would be fine, I just truly see no need to take away the lone safe hex in the zone (not safe when the lurker can still kill you there), but just safe from the NV snipers. That basically makes it so that I will never take a wizard to -300 without other people there, it just isn’t worth the hassle.

**Comment by Wirednuke** [comment]
I leveled from 15 to 17 magic during the pandemic sitting in the pool on -300 on the Lands of Kesmai server. That's with gargs, the pillar, death casters.. the whole shabang. The solution is pretty simple... You set recalls, and you recall down to burn mana, and then recall back to town when you're afk.

**Comment by Chilly021** [comment]
Think we are good here.
