### ISSUE TITLE
Concussion

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#338]
unable to cast onto dark hex.  100% chance to destroy walls should prob be nerfed. [Reported by Palad]

**Comment by jkachhad** [comment]
The ability to destroy walls is based on the damage output. Walls are destroyed when damage is greater than 40, and tress when damage is greater than 30. Damage is determined by (8 * skill level) at the center, then diminishes by half each tile out.

If you can suggest what you believe would be appropriate levels where walls can be broken, I can implement as such. At the moment, A wall in the center can be broken at level 5, 1 tile out at level 10, 2 tiles out at level 20.

**Comment by dedmist** [comment]
Cyxel put out a lor casting 19 concussion all over the place.  In a 5x5, there seems to be around a 5-10% chance per wall to blow them.  It's good to have a low chance, so that when you use concussion for hunting it doesn't level the whole area.  Breaking walls too often would destroy the viability of DJ/conc hunting, and limit the usefulness of conc for ranged on wizards.  However, there's a much higher chance to break walls if there are 2 concussions on it in the same round.
For instance, when I'm concussion hunting on a thaum, I generally only blow a few walls in an entire circuit, using a single DJ.  However, if I want to level something, I use 2 djs, and can knock down any set of walls in a few rounds.
There is a threshold, wizards have to make it to a certain skill to blow a wall, and the percentage per wall doesn't seem to increase, but the number of walls in the blast radius increases, giving a much higher chance to blow alot of walls at a time.

lors:
One of Cyxel and one of a Thaum conc hunting
https://www.dropbox.com/sh/q85hdm6pbo5btgd/AABcUjQtxSigy_U62jIubIK8a?dl=0

**Comment by jkachhad** [comment]
Changed similarly to how you described, there is a % chance linked to skill level and a minimum skill requirement.
