### ISSUE TITLE
Automatic pathing

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#382]
When navigating the Oak town canopy, automatic pathing does not prioritize land from sky, and turning a corner, if not customized by the EU to avoid sky hexes, will shortcut through those sky hexes, dropping the player to the ground below. [Suggested by RaloMyth]

**Comment by jkachhad** [comment]
I've identified that this may be occurring in specific cases. When a door opens due to another trigger, the client properly updates the visibility and flags of that tile. However, when pathing into the door, the client does receive the update for flags.

The server queues the tile to update the flag, but the visibility updates are sent immediately and before the update can occur. So, this visibility state updates, but not the tile flags.  The solution would be either updating the tile when the door opens or delaying the visibility updates.

**Comment by jkachhad** [comment]
Fixed, but i'll document the following for myself.

Two VisibilityUpdates occured in this scenario, one when the player moved, and another when the door opened. The door component updates the flags of the tile immediately, and the player's visibility is updated immediately now.  There was another bug when previousVisibility equaled currentVisibility, but a update was sent anyways (27b). It likely only occurs in this scenario.  The fix now checks proper equality.

UpdateVisibility() can now return default when previousVisibility.Equals(currentVisibility).  Delta changes handles the case of null to prevent sending an unnecessary update.  The following usages do not:

- Game\Entities\Mobiles\MobileEntity.Movement.cs
- Game\States\WorldState.cs
