### ISSUE TITLE
Pathing doesnt take advantage of water walk

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#479]
[Reported by surf]

**Comment by surfotato** [comment]
Some examples to consider.
![image](https://user-images.githubusercontent.com/85204505/120598787-8d507500-c3fb-11eb-882a-5e5f1cb4ad3f.png)
![image](https://user-images.githubusercontent.com/85204505/120598857-a0634500-c3fb-11eb-9329-aea39d23dc6d.png)

**Comment by surfotato** [comment]
May be different, here it doesn't use the lower cost and feasible path to the left.

![image](https://user-images.githubusercontent.com/85204505/120601613-07362d80-c3ff-11eb-893d-0a0710eab66d.png)

**Comment by jkachhad** [comment]
After modifying the cost for ruins to 3.

Case #1: The cost here is equal since the ruins interrupt movement, as does the water. You would reach your target after 2 turns.
Case #2: You would reach your target after 3 turns walking through water vs. 2 going by land first.

Case #3: This should be fixed to provider a better path that minimizes number of turns.
![image](https://user-images.githubusercontent.com/1934897/120722009-c92f1d00-c483-11eb-813b-06c03d2177d7.png)
