### ISSUE TITLE
SGA isn't true "2 hander"

### ISSUE THREAD

**Issue by SewerCzar** [jkachhad/Stormhalter#555]
SGA can be wielded in one hand with the raxe and swings normally. BBS this was proper, SGA was a "true two hander" in the OG. Didn't test other twohanded weapons.

**Comment by sproatba** [comment]
So twohanded weapons in the og when right clicked would say you can use this weapon with two hands.  Once you reached a certain skill they would change and say you can use this weapon with one or two hands.   BBS this happened fairly early, like skillful.  SGA happened later, I want to say brilliant.   Until this point you fumbled if you tried to swing with an item in the left hand.  Is this a mechanic we want for two hand in general, or perhaps just certain ones should be true two handers?   Currently, they are basically 1h weapons except for when using a shield.

**Comment by Chilly021** [comment]
We can mark this as a bug for now because it is affecting HC gameplay. Granted it will change most people's idea of using a 2h, but this will maybe get some discussions going for Khally polekick and other items. 

Any new implementation of a weapon should have this taken into account until this is fixed.

**Comment by jkachhad** [comment]
Fixed in the next build.
