### ISSUE TITLE
Shields not adding "Defense value"

### ISSUE THREAD

**Issue by SewerCzar** [jkachhad/Stormhalter#572]
![defensevalue1](https://user-images.githubusercontent.com/86573170/124638006-7668cc80-de58-11eb-9536-c6c9a93d5ebc.PNG)
![defensevalue2](https://user-images.githubusercontent.com/86573170/124638014-78329000-de58-11eb-91d7-e07875a30e2d.PNG)

**Comment by jkachhad** [comment]
When the ratings are evaluated, they are not against specific item, but a `null` type. The shields only provide a bonus against a `weapon` type, and not other types, say for example a gem. The defense won't apply since we're not calculating against a weapon. We'll have to keep this in mind.  I'll enable debug messages for combat that show you actual values when attacking or defending.
