### ISSUE TITLE
Summoned Phantasms movement speed

### ISSUE THREAD

**Issue by jkachhad** [jkachhad/Stormhalter#62]
A tester reported that summon phantoms, djinns, and efreets should move 3 spaces at a time when following. My memory, at least from Gamestorm, was that you always had to wait for them.

**Comment by dedmist** [comment]
Ya, summoned creatures moved 2 hexes in the OG, this is useful for ice djs, because it's quicker to get off an ice attack from 1 hex away than to move the dj offhex then ice, or have to manually move ice djinns or  bait creatures and have them follow back to a standing ice djinn.  However, it's annoying for concussion or efreets.  Attila's game had 3 hex movement.  It'd be nice to have a "stand one hex behind" command, which you could do in Attila's game by handing them a halberd, but you can't carry around a bunch of halberds to do this consistently.

**Comment by jkachhad** [comment]
Suggestions for the command? "trail"
Entities would determine their trail position by calculating the normal path to "follow," and then simply stopping 1 short.

**Comment by jkachhad** [comment]
Added for the next update v0.13-
You can direct entities to "trail" you, they will stop 1 short of their follow path. Keep in mind, when entities are trailing, you must still maintain LOS. The outcome is that when entities trail you, you must also move 2 hexes at a time as moving 3 will put you out of LOS.
