### ISSUE TITLE
Leng - Tile Interface Error - Ninja Back Stairs

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#682]
Tiles in back stair case default to "Open" not "Move" [Report by Amedi]

**Comment by yarrim** [comment]
Pretty sure this is staticID 183. Also seems to be happening with staticID 182 in the "Green floor dungeon." Nothing looks incorrect about these tiles in WorldForge. This 'open' vs 'move' issue sometimes prevents players from moving into a tile via mouse, though a command like 'e' works to move them on and then fixes the issue client-side.

**Comment by yarrim** [comment]
Adding to this, the issue with pathing through water seems to be that the client doesn't recognize the new water tiles, like 601 as being water tiles. Since the MovementCost is probably server-side, the client should probably be sent the same ComponentResource that Worldforge gets on startup to figure out what each static is likely to be - or the server should send component type to the client when telling it about the world around the player.
