### ISSUE TITLE
Skill re-gain functioning improperly

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#711]
I died and went down 2 skill levels, my critique was stuck at 72% into 13. Didnt move. I logged a few times, paused, and when it finally boosted it went directly to 72% into 14. I believe my cap is 72% into 15 so it's waiting on full level gains to re-gain skill? [Report by Sewer]

**Comment by jkachhad** [comment]
It's waiting on full levels to tell you you're at that level.  It should continue to gain in the background.  Maybe we should not let the player know when they cross a full level if they are under their achieved skill level?

**Comment by SewerCzar** [comment]
Waiting until 72% into the next level creates an issue where spells fizzle - for melee / other components it's fine but when you go from "Lord of Fire" to "Master of Air" 72% and don't hit "Mage" until 72% in you're spending 3x longer being incapable of casting ice spear than you would in OG / lands

**Comment by trlook** [comment]
It's not actually waiting until 72%. when you get back to say 14.00 and go to critique it would say you are 72% into Mage and below your potential.  I think it also knocks you from 15.72 down to 13.00 which is why it does feel like you have to get a whole level before you level up again.  The bug here is how critique reports skill, it gets the integer part right but it's reporting the percentage based on the highest acquired rather than the current.

**Comment by SewerCzar** [comment]
That's interesting. I know you said the stat boosts from the skill were regained RE: melee and defense showing up but it's still impossible to cast Ice Spear until you get the "You have reached the level of Mage!" ding at 72% into mage so it's definitely more than a cosmetic issue though.

**Comment by trlook** [comment]
What I'm saying is that "You have reached the level of Mage!" is really occurring at 14.00 skill even though critique says 14.72 and below your potential.

**Comment by SewerCzar** [comment]
So then I'm losing 2.72 skill levels per death and going to 13.72 in that scenario from 15.72? I very much doubt that's part of the calculation. I don't think it's a critique error.

I very much believe it's just set to a 0 skill counter and display "You gain a skill level!" when you hit one level up from death-set skill.

**Comment by trlook** [comment]
> 
> 
> So then I'm losing 2.72 skill levels per death and going to 13.00 in that scenario from 15.72? I very much doubt that's part of the calculation. I don't think it's a critique error.
> 
> I very much believe it's just set to a 0 skill counter and display "You gain a skill level!" when you hit one level up from death-set skill.

Based on what I'm seeing with my skills and attack ratings when I die I go from like 14.64 -> 12.00 and my critique says 12.64.

**Comment by trlook** [comment]
So there are two issues here, how critique reports and how much skill you lose when you die.  Currently it appears that you lose 2 whole skills levels plus your progress into the next level i.e. 15.72->13.00 on death.  Proposal would be to lose only the two skill levels i.e. 15.72->13.72.  Separately, there is a critique display issues where critique reports your highest attained skill rather than your current progress when you are below your potential.  The first issues, how much skill to loose is ultimately a design choice, how punishing should death be?  Second issues is IMO a bug.

**Comment by Tawnos-LOK** [comment]
Closing for now with the phasing out of the death penalty system. When the next version gets implemented, we'll retest these sorts of items.
