### ISSUE TITLE
problem with green floor tile 182

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#723]
There seems to be a problem with green floor tiles (ground 182) that causes issues moving to them some times. [Reported by HealthySnack]

**Comment by yarrim** [comment]
see also https://github.com/jkachhad/Stormhalter/issues/682  - issue with 183; also looking like the client sees it as a door?

**Comment by yarrim** [comment]
Adding to this, the issue with pathing through water seems to be that the client doesn't recognize the new water tiles, like 601 as being water tiles. Since the MovementCost is probably server-side, the client should probably be sent the same ComponentResource that Worldforge gets on startup to figure out what each static is likely to be - or the server should send component type to the client when telling it about the world around the player.

**Comment by trlook** [comment]
Evidence points to client seeing this tile as a door.  Can move to green tiles from 2 or more spaces away (but still gives "open" context) but can't from 1 space away.
