### ISSUE TITLE
-2 Oak bug hex

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#759]
if you portal the wall directly above the 1 hex water at the jump into -2 hobs can walk on that hex after its destroyed and never leave, it traps them to it [Report by Thiefy]

**Comment by jkachhad** [comment]
As of version 0.79, this issue does not appear to be occurring. I created a portal, used find secret doors to blow the wall, spawned a hobgoblin, and it appeared to move around fine. 

I think believe this may have been occurring when visibility was changed to *per tile*, but that tile had no visibility because of the wall. Creating portal now trigger the visibility to be updated.
